GatewayInterface wlan0
FirewallRuleSet authenticated-users {
  FirewallRule allow all
}

FirewallRuleSet preauthenticated-users {
FirewallRule allow tcp port 53
FirewallRule allow udp port 53
}

FirewallRuleSet users-to-router {
  FirewallRule allow udp port 53	
  FirewallRule allow tcp port 53	
  FirewallRule allow udp port 67
  FirewallRule allow tcp port 22
  FirewallRule allow tcp port 80
  FirewallRule allow tcp port 443
}

GatewayAddress 10.3.141.1
StatusPage status.html
RedirectURL https://www.google.com/
MaxClients 250
SessionTimeout 120
DebugLevel 0
